version: '1.0'
services:
  database:
    image: postgres:16
    container_name: db_dev_trampo
    environment:
      POSTGRES_DB: dev_trampo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: