version: '1.0'
services:
  # api_alfood:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: api_alfood
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - alfood_bridge
  #   depends_on:
  #     - alfood_db
  #   environment:
  #     DATABASE_URL: 'postgres://postgres:teste@alfood_db:5432/alfood'
  #     WAIT_HOSTS: postgres:5432
  #     WAIT_HOSTS_TIMEOUT: 300
  #     WAIT_SLEEP_INTERVAL: 30
  #     WAIT_HOST_CONNECT_TIMEOUT: 30
  #   command: sh -c "npm run migrate up && npm run dev"

  dev_trampo_db:
    image: postgres:16
    container_name: dev_trampo_db
    environment:
      POSTGRES_DB: dev_trampo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - dev_trampo_bridge
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


networks:
  dev_trampo_bridge:
    driver: bridge
